#!/usr/bin/bash
# updateCert - Atualiza certificado
#
# Author: Oliver, <https://programadorboard.epizy.com>
#
#

date=", Date: $(date +%d/%m/%y) - $(date +%H:%M) e $(date +%S) segundos"
comment_crt="BEGIN CERTIFICATE"
comment_key="BEGIN PRIVATE KEY"
author="By: oliver, "
file="File: cert"
dir=apache/ssl
dir_other=$PREFIX/etc/apache2/ssl
command="grep -Eo"

# Baixar certificado novo
update() {
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ${dir}/${file:6}.key -out ${dir}/${file:6}.crt
}

# Subsitue uma string
regex() {
    sed -i "s|${comment_crt}|${author}${file}.crt${date}|g" ${dir}/${file:6}.crt
    sed -i "s|${comment_key}|${author}${file}.key${date}|g" ${dir}/${file:6}.key
}

# Copia novos arquivos
copy() {
    cp ${dir}/${file:6}.crt $dir_other
    cp ${dir}/${file:6}.key $dir_other
}

# Verifica certificado atualizado
verify() {
    local regex="${author:0:3}.*${date:57}"
    local crt="$($command $regex ${dir_other}/${file:6}.crt)"
    local key="$($command $regex ${dir_other}/${file:6}.key)"

    [ -n "$crt" -a -n "$key" ] && echo "[+] Certificado atualizado" && exit 0
    [ -z "$crt" -a -z "$key" ] && echo "[!] Falhou ao atualizar o certificado!" && exit 1
    [ -n "$crt" -a -z "$key" ] && echo "[!] Falhou ao atualizar o certificado!" && exit 1
    [ -z "$crt" -a -n "$key" ] && echo "[!] Falhou ao atualizar o certificado!" && exit
}

update
regex
copy
verify
