#!/usr/bin/bash
# updateCert - Atualiza certificado
#
# Author: Oliver, <https://programadorboard.epizy.com>
#
#

dir=apache/ssl
dir_other=$PREFIX/etc/apache2/ssl

# Baixar certificado novo
update() {
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ${dir}/cert.key -out ${dir}/cert.crt
}

# Copia novos arquivos
copy() {
    cp ${dir}/cert.crt $dir_other
    cp ${dir}/cert.key $dir_other
}

# Verifica certificado atualizado
verify() {

    [ -f $PREFIX/etc/apache2/ssl/cert.crt -a -f $PREFIX/etc/apache2/ssl/cert.key ] && echo "[+] Certificado atualizado" && exit 0
}

update
copy
verify
